import type { Metadata } from "next";
import "./globals.css";
import { Fira_Code } from "next/font/google"
import Provider from "../utils/Provider";
import Navbar from "../components/Navbar";

const firaCode = Fira_Code({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} h-full bg-amber-100 text-indigo-950 dark:bg-slate-950 dark:text-amber-100 dark:selection:bg-purple-500`}>
        <Provider>
        <Navbar /> 
        <main className="mx-auto max-w-5xl px-6">
        {children}
        </main>
        </Provider>
      </body>
    </html>
  );
}
